# Generated by Django 4.1 on 2022-08-15 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True, verbose_name='status')),
                ('name', models.CharField(help_text='Customer name', max_length=250, verbose_name='Customer name')),
                ('email', models.EmailField(help_text='Customer email', max_length=254, verbose_name='Customer email')),
                ('document', models.PositiveIntegerField(help_text='Customer document', verbose_name='Customer document')),
                ('birth_date', models.DateField(help_text='Customer birth date', verbose_name='Customer birth date')),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
            },
        ),
    ]
