# Generated by Django 4.1 on 2022-08-15 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(help_text='Name', max_length=250, verbose_name='Customer name'),
        ),
    ]
